### ISSUE TITLE
Create new repo `getditto/template-app-csharp-todo`: 

### ISSUE THREAD

**Issue by okdistribute** [getditto/samples#134]
Create new repo `getditto/template-app-csharp-todo` based on https://github.com/getditto/samples/tree/main/tasks/csharp

There are significant issues with this example, though.  It is doing more complicated use-case specific things, which it should not do as a getting started example.

- [x] Should not be manually setting the transport configurations
- [x] It is using offline playground, but should be using online playground.
- [x] Update the README
- [x] Make the repository public.
- [x] Update the SAMPLES readme (this repo) to point to the new repository
- [x] Delete the csharp example from this repo

**Comment by texasRanger09** [comment]
New Repo
https://github.com/getditto/template-app-csharp-todo
